### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by chriszarate** [makotot/scrollspy#1]
(Thanks for this plugin—it's very nice to have a pure JS implementation. I have it working very well in one of my projects.)

Even though this is a browser library, I'd be grateful if you could publish this to NPM so that it could be more easily require'd. (I did notice that the `scrollspy` package name is taken—bummer.)

Thanks again!

**Comment by makotot** [comment]
@chriszarate 
`scrollspy` is already taken by another package as you say. So if I want to publish this lib to npm registry without changing this lib name, "scoped package" only can do it.
So [scoped package](https://docs.npmjs.com/getting-started/scoped-packages) works with npm **v2.7.0+**, people who use lessser than v2.6.0 need to update npm with `npm i -g npm`.
If you think that no problem, I will publish this lib as scoped package and you can install it with `npm i @makotot/scrollspy`.
Any other solutions?

**Comment by chriszarate** [comment]
I didn't know about scoped NPM packages. I had assumed that you would just publish to NPM using a different name. Changing the lib name in `package.json` shouldn't break anything. It would mean having a different package name in Bower vs NPM, but `@makotot/scrollspy` is effectively a different package name, too.

I'm totally fine with whatever works best for you. I can certainly work with a scoped package.

**Comment by makotot** [comment]
> Changing the lib name in package.json shouldn't break anything. It would mean having a different package name in Bower vs NPM, 

Yes, I didn't want to change this lib name bacase this lib already had registered as `scrollspy` in bower.

> but @makotot/scrollspy is effectively a different package name, too.

Yes, indeed! Anyway I have to be registered with different name in bower and npm. I will change the name in package.json and publish to npm soon.

**Comment by chriszarate** [comment]
Thanks!

**Comment by makotot** [comment]
Done! You can install this lib from npm with 

``` sh
$ npm install --save scrollspy-js
```

**Comment by chriszarate** [comment]
Works beautifully. Thanks again for writing this library.
